import { Theme } from '@radix-ui/themes';
import "@radix-ui/themes/styles.css";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,400;0,700;1,400;1,700&family=PT+Serif:wght@400;700&display=swap" rel="stylesheet"/>
      </head>
      <body>
        <Theme accentColor="amber">
        {children}
        </Theme>
      </body>
    </html>
  );
}
