import { Theme } from '@radix-ui/themes';
import "@radix-ui/themes/styles.css";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Theme accentColor="amber">
        {children}
        </Theme>
      </body>
    </html>
  );
}
